### PR TITLE
clang-tidy: use override

### PR DESCRIPTION
**Pull request by neheb**
Found with modernize-use-override

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by kjellahl** [comment]
Why have you removed `override` in tests/istream_ioparser/main.cc?

**Comment by neheb** [comment]
override and final are the same thing. No need for both. It was clang-tidy that did this.

**Comment by kjellahl** [comment]
The CI pipeline failed. gcc 8 does not understand that `final` implies `override`.
It issues error messages such as
```
test_streambuf::underflow()’ can be marked override [-Werror=suggest-override]
```
I've replaced `final` by `override`.

**Comment by neheb** [comment]
Weird. Bug in GCC8 I guess. No real difference between override and final anyway.

**Pull request merged**
