### PR TITLE
Replace Visual Studio 2010 projects with NMake Makefiles (master branch)

### PR DESCRIPTION
**Pull request by fanc999**
Hi,

The existing Visual Studio 2010 projects are known to be broken, and Visual Studio 2010 is known not to be sufficient to build the C++-17 code in libxml++ master.  So, this attempts to fix this by adding a set of NMake Makefiles to replace the Visual Studio projects, as:

*  This consumes `filelist.am` in libxml++/, so that we don't have to worry about the source listings going out-of-sync.
*  This is made to be more flexible in terms of updating versions and various flags, and supports building directly from a GIT checkout with the `prep-git-build` target.

There are some minor source updates as well so that we can ensure the sources continue to build on Visual Studio.

I am a bit curious about the status of the `libxml++-4-0` branch, since it remained stale for some time and the source file `exception.cc` had problems building against glibmm master's `ustring.h`, due to variadic template usage for the variable `args` that seems like a mismatch with today's glibmm master.

With blessings, thank you!

### CODE REVIEW

**Comment by kjellahl** [comment]
libxml++-2.6 (libxml++-2-42 branch)  
Requires C++11, sigc++-2.0 and glibmm-2.4. libxml++-2.6 is old. No new releases
for almost 5 years. I will probably not add Meson support. I don't expect more
releases in the future, unless someone very urgently needs one.

libxml++-3.0 (libxml++-3-2 branch)  
Requires C++11, sigc++-2.0 and glibmm-2.4.

libxml++-4.0 (libxml++-4-0 branch)  
Requires C++17, sigc++-3.0 and glibmm-2.66.

libxml++-5.0 (master branch)  
Requires C++17. Does not depend on sigc++ or glibmm.
I'm not sure it actually needs a C++17 compiler. But it's required in configure.ac,
and I think we should keep it like that. It gives us the freedom to use C++17
features in the future, even if it's not used today. I think libxml++-4.0 requires
C++17 only because it depends on sigc++-3.0 and glibmm-2.66.

What's the problem with the libxml++-4-0 branch? The code can be built with the gcc compiler.


Two comments on this PR:

1. The code in the master branch does not depend on libsigc++. If you have found
such a dependency, it's wrong, and shall be fixed.

2. \_\_PRETTY_FUNCTION\_\_ in node.cc seems unnecessary.
```
      std::cerr << __PRETTY_FUNCTION__ << " Warning: new node of unknown type created: "
                << node->type << std::endl;
```
can be replaced by
```
      std::cerr <<  "xmlpp::Node::create_wrapper(): Warning: new node of unknown type created: "
                << node->type << std::endl;
```

Do you want me to merge this PR as is, or do you want to change anything before I do that?

**Comment by fanc999** [comment]
Hi @kjellahl,

I think it would be best if I look into the issues before the commits here go in, and I think I did not use `/std:c++17` in the compiler flags, which can be required to activate full C++17 support (which I need to check also for the `libxml++-4-0` branch), so I think I should just activate this flag for `master` and `libxml++-4-0`.

I think for the `libxml++-3-2` branch, I need to check harder whether there are any flags that could bring down the requirements to Visual Studio 2015, as the other C++-11 branches in the -mm libraries do only require Visual Studio 2015 or later, but anyways...

Thanks though, and cheers!

**Comment by fanc999** [comment]
Hi @kjellahl,

I fixed the issues you pointed out for this PR , and indeed we can go without `libsigc++` as well here.  I also enabled the `/std:c++17` compiler flag here as well.

For the `libxml++-4-0` branch, I will open a PR soon (#11) , as the build failure had to do with me forgetting to use `/std:c++17`, so, yes, C++-17 is required for the `libxml++-4-0` branch.

For the `libxml++-3-2` branch, due to the compiler bug that disallows using `explicit` with `virtual` nor `override`, only Visual Studio 2017 or later is supported.

With blessings, thank you!

**Comment by fanc999** [comment]
Hi @kjellahl,

Thanks a bunch!

**Pull request merged**
